language: python
python:
  - 3.6
  - 3.7
  - 3.8

env:
  global:
    CC_TEST_REPORTER_ID=a33b246cb31644fa98afeefa5b3601fe97e021b553bf1d49379980824adb6f54

before_install:
  # make depends on poetry
  - pip install poetry

install:
  - make install

script:
  - make lint
  - make tests

after_script:
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/backend/.resultset.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage;
