[tool.poetry]
name = "gendiff"
version = "0.1.0"
description = "Shows difference between two config files"
authors = ["Ana-ana"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
